name: Release APK
description: Build a signed release APK of your Android application

branding:
  icon: cpu
  color: red

inputs:
  keystore:
    description: The keystore file in base64 encoded format
    required: true

  keystore-password:
    description: The password of the keystore file
    required: true

  key-alias:
    description: The key alias
    required: true

  key-password:
    description: The password for the key
    required: true

  java-version:
    description: The Java version to set up
    # https://developer.android.com/build/releases/gradle-plugin?hl=en#compatibility
    default: "17"

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java_version }}

    - name: Decode keystore
      shell: node {0}
      run: |
        require('fs').writeFileSync(
          '${{ runner.temp }}/.jks',
          '${{ inputs.keystore }}',
          'base64'
        );

    - name: Release APK
      shell: sh
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file='${{ runner.temp }}/.jks' \
          -Pandroid.injected.signing.store.password='${{ inputs.keystore_password }}' \
          -Pandroid.injected.signing.key.alias='${{ inputs.key_alias }}' \
          -Pandroid.injected.signing.key.password='${{ inputs.key_password }}'
