name: "Build Signed APK"
description: "Build a signed APK of your Android application"

branding:
  icon: cpu
  color: red

inputs:
  keystore:
    description: "The contents of the keystore file, encoded as base64"
    required: false

  keystore_password:
    description: "Keystore file password"
    required: true

  key_alias:
    description: "Key alias"
    required: true

  key_password:
    description: "Key password"
    required: true

  java_version:
    description: "Java version to build the project with"
    required: false
    default: "17"

runs:
  using: "composite"
  steps:
    # - name: Setup Java
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: temurin
    #     java-version: ${{ inputs.java_version }}

    - name: Write keystore file from content
      if: inputs.keystore
      shell: bash
      run: echo "${{ inputs.keystore }}" | base64 -d > "$GITHUB_WORKSPACE/.jks"

    - name: Build APK
      shell: bash
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file="$GITHUB_WORKSPACE/.jks" \
          -Pandroid.injected.signing.store.password="${{ inputs.keystore_password }}" \
          -Pandroid.injected.signing.key.alias="${{ inputs.key_alias }}" \
          -Pandroid.injected.signing.key.password="${{ inputs.key_password }}"
