name: Release APK
description: Build a signed release APK of your Android application

branding:
  icon: cpu
  color: red

inputs:
  keystore:
    description: The keystore file in base64 encoded format
    required: true
  keystore-password:
    description: The password of the keystore file
    required: true
  key-alias:
    description: The key alias
    required: true
  key-password:
    description: The password for the key
    required: true

  # https://developer.android.com/build/releases/gradle-plugin?hl=en#compatibility
  java-version:
    description: The Java version to set up
    default: "17"

  gradle-args:
    description: The arguments passed to Gradle
    default: "--no-daemon"

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
        cache: gradle

    - shell: node {0}
      run: |
        //Decode keystore
        require('fs').writeFileSync(
          '${{ runner.temp }}/.jks',
          '${{ inputs.keystore }}',
          'base64'
        );

    - shell: sh
      run: |
        #Release APK
        chmod +x ./gradlew

        ./gradlew assembleRelease $GRADLE_ARGS \
          -Pandroid.injected.signing.store.file='${{ runner.temp }}/.jks' \
          -Pandroid.injected.signing.store.password='${{ inputs.keystore-password }}' \
          -Pandroid.injected.signing.key.alias='${{ inputs.key-alias }}' \
          -Pandroid.injected.signing.key.password='${{ inputs.key-password }}'
      env:
        GRADLE_ARGS: ${{ inputs.gradle-args }}
