name: APK action
description: Build a signed, release-ready APK with GitHub Actions

branding:
  icon: package
  color: red

inputs:
  keystore:
    description: Contents of the keystore file (.jks), base64 encoded
    required: true
  keystore-password:
    description: Password of the keystore
    required: true
  key-alias:
    description: Alias of the key
    required: true
  key-password:
    description: Password of the key
    required: true

  # https://developer.android.com/build/releases/gradle-plugin?hl=en#compatibility
  java-version:
    description: The Java version to set up
    default: '17'
  gradle-args:
    description: The arguments passed to Gradle
    default: --no-daemon

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
        cache: gradle

    - shell: sh
      env:
        TMPDIR: ${{ runner.temp }}
      run: echo "KEYSTORE_PATH=$(mktemp)" >>"$GITHUB_ENV"

    - shell: sh
      working-directory: ${{ github.action_path }}
      run: ./keystore.js '${{ inputs.keystore }}'

    - shell: sh
      run: |
        #Release APK
        chmod +x ./gradlew

        ./gradlew assembleRelease $GRADLE_ARGS \
          -Pandroid.injected.signing.store.file='${{ env.KEYSTORE_PATH }}' \
          -Pandroid.injected.signing.store.password='${{ inputs.keystore-password }}' \
          -Pandroid.injected.signing.key.alias='${{ inputs.key-alias }}' \
          -Pandroid.injected.signing.key.password='${{ inputs.key-password }}'
      env:
        GRADLE_ARGS: ${{ inputs.gradle-args }}
